import { Category } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-makanan',
    name: 'Makanan & Minuman',
    icon: 'restaurant-outline',
    color: '#F59E0B',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-belanja',
    name: 'Belanja Bulanan',
    icon: 'cart-outline',
    color: '#10B981',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-transportasi',
    name: 'Transportasi',
    icon: 'car-outline',
    color: '#3B82F6',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-tagihan',
    name: 'Tagihan & Utilitas',
    icon: 'flash-outline',
    color: '#8B5CF6',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-hiburan',
    name: 'Hiburan & Rekreasi',
    icon: 'game-controller-outline',
    color: '#EC4899',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-kesehatan',
    name: 'Kesehatan & Medis',
    icon: 'medkit-outline',
    color: '#EF4444',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-pendidikan',
    name: 'Pendidikan & Buku',
    icon: 'book-outline',
    color: '#06B6D4',
    type: 'expense',
    is_default: true,
  },
  {
    id: 'cat-pendapatan',
    name: 'Gaji & Pendapatan',
    icon: 'wallet-outline',
    color: '#10B981',
    type: 'income',
    is_default: true,
  },
  {
    id: 'cat-lainnya',
    name: 'Lainnya',
    icon: 'ellipsis-horizontal-circle-outline',
    color: '#6B7280',
    type: 'expense',
    is_default: true,
  },
];
